/*
 * This file is generated by jOOQ.
 */
package com.fyle.banks.repository.model.jooq;


import com.fyle.banks.repository.model.jooq.tables.Banks;
import com.fyle.banks.repository.model.jooq.tables.Branches;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BANKS_ID_PKEY = Indexes0.BANKS_ID_PKEY;
    public static final Index BRANCHES_IFSC_PKEY = Indexes0.BRANCHES_IFSC_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BANKS_ID_PKEY = Internal.createIndex("banks_id_pkey", Banks.BANKS, new OrderField[] { Banks.BANKS.ID }, true);
        public static Index BRANCHES_IFSC_PKEY = Internal.createIndex("branches_ifsc_pkey", Branches.BRANCHES, new OrderField[] { Branches.BRANCHES.IFSC }, true);
    }
}
