/*
 * This file is generated by jOOQ.
 */
package com.fyle.banks.repository.model.jooq.tables.records;


import com.fyle.banks.repository.model.jooq.tables.BankBranches;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankBranchesRecord extends TableRecordImpl<BankBranchesRecord> implements Record8<String, Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = -197403684;

    /**
     * Setter for <code>public.bank_branches.ifsc</code>.
     */
    public void setIfsc(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bank_branches.ifsc</code>.
     */
    public String getIfsc() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.bank_branches.bank_id</code>.
     */
    public void setBankId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bank_branches.bank_id</code>.
     */
    public Long getBankId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.bank_branches.branch</code>.
     */
    public void setBranch(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bank_branches.branch</code>.
     */
    public String getBranch() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bank_branches.address</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bank_branches.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bank_branches.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bank_branches.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.bank_branches.district</code>.
     */
    public void setDistrict(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bank_branches.district</code>.
     */
    public String getDistrict() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.bank_branches.state</code>.
     */
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.bank_branches.state</code>.
     */
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.bank_branches.bank_name</code>.
     */
    public void setBankName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.bank_branches.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Long, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Long, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BankBranches.BANK_BRANCHES.IFSC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BankBranches.BANK_BRANCHES.BANK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BankBranches.BANK_BRANCHES.BRANCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BankBranches.BANK_BRANCHES.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BankBranches.BANK_BRANCHES.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BankBranches.BANK_BRANCHES.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return BankBranches.BANK_BRANCHES.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return BankBranches.BANK_BRANCHES.BANK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getIfsc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getBankId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBranch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBankName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIfsc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getBankId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBranch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBankName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value1(String value) {
        setIfsc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value2(Long value) {
        setBankId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value3(String value) {
        setBranch(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value4(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value5(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value6(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value7(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord value8(String value) {
        setBankName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankBranchesRecord values(String value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankBranchesRecord
     */
    public BankBranchesRecord() {
        super(BankBranches.BANK_BRANCHES);
    }

    /**
     * Create a detached, initialised BankBranchesRecord
     */
    public BankBranchesRecord(String ifsc, Long bankId, String branch, String address, String city, String district, String state, String bankName) {
        super(BankBranches.BANK_BRANCHES);

        set(0, ifsc);
        set(1, bankId);
        set(2, branch);
        set(3, address);
        set(4, city);
        set(5, district);
        set(6, state);
        set(7, bankName);
    }
}
